// This file was auto-generated by generate_types in the remote crate.
// Do not edit manually.

// Electric row types
export type JsonValue = number | string | boolean | Array<JsonValue> | { [key in string]?: JsonValue } | null;

export type Project = { id: string, organization_id: string, name: string, color: string, created_at: string, updated_at: string, };

export type Notification = { id: string, organization_id: string, user_id: string, notification_type: NotificationType, payload: JsonValue, issue_id: string | null, comment_id: string | null, seen: boolean, dismissed_at: string | null, created_at: string, };

export type NotificationType = "IssueCommentAdded" | "IssueStatusChanged" | "IssueAssigneeChanged" | "IssueDeleted";

export type Workspace = { id: string, project_id: string, owner_user_id: string, issue_id: string | null, local_workspace_id: string | null, archived: boolean, files_changed: number | null, lines_added: number | null, lines_removed: number | null, created_at: string, updated_at: string, };

export type ProjectStatus = { id: string, project_id: string, name: string, color: string, sort_order: number, hidden: boolean, created_at: string, };

export type Tag = { id: string, project_id: string, name: string, color: string, };

export type Issue = { id: string, project_id: string, issue_number: number, simple_id: string, status_id: string, title: string, description: string | null, priority: IssuePriority, start_date: string | null, target_date: string | null, completed_at: string | null, sort_order: number, parent_issue_id: string | null, parent_issue_sort_order: number | null, extension_metadata: JsonValue, created_at: string, updated_at: string, };

export type IssueAssignee = { id: string, issue_id: string, user_id: string, assigned_at: string, };

export type IssueFollower = { id: string, issue_id: string, user_id: string, };

export type IssueTag = { id: string, issue_id: string, tag_id: string, };

export type IssueRelationship = { id: string, issue_id: string, related_issue_id: string, relationship_type: IssueRelationshipType, created_at: string, };

export type IssueRelationshipType = "blocking" | "related" | "has_duplicate";

export type IssueComment = { id: string, issue_id: string, author_id: string, parent_id: string | null, message: string, created_at: string, updated_at: string, };

export type IssueCommentReaction = { id: string, comment_id: string, user_id: string, emoji: string, created_at: string, };

export type IssuePriority = "urgent" | "high" | "medium" | "low";

export type PullRequestStatus = "open" | "merged" | "closed";

export type PullRequest = { id: string, url: string, number: number, status: PullRequestStatus, merged_at: string | null, merge_commit_sha: string | null, target_branch_name: string, issue_id: string, workspace_id: string | null, created_at: string, updated_at: string, };

export type UserData = { user_id: string, first_name: string | null, last_name: string | null, username: string | null, };

export type User = { id: string, email: string, first_name: string | null, last_name: string | null, username: string | null, created_at: string, updated_at: string, };

export enum MemberRole { ADMIN = "ADMIN", MEMBER = "MEMBER" }

export type OrganizationMember = { organization_id: string, user_id: string, role: MemberRole, joined_at: string, last_seen_at: string | null, };

export type CreateProjectRequest = { 
/**
 * Optional client-generated ID. If not provided, server generates one.
 * Using client-generated IDs enables stable optimistic updates.
 */
id?: string, organization_id: string, name: string, color: string, };

export type UpdateProjectRequest = { name: string | null, color: string | null, };

export type CreateNotificationRequest = { 
/**
 * Optional client-generated ID. If not provided, server generates one.
 * Using client-generated IDs enables stable optimistic updates.
 */
id?: string, organization_id: string, seen: boolean, };

export type UpdateNotificationRequest = { seen: boolean | null, };

export type CreateTagRequest = { 
/**
 * Optional client-generated ID. If not provided, server generates one.
 * Using client-generated IDs enables stable optimistic updates.
 */
id?: string, project_id: string, name: string, color: string, };

export type UpdateTagRequest = { name: string | null, color: string | null, };

export type CreateProjectStatusRequest = { 
/**
 * Optional client-generated ID. If not provided, server generates one.
 * Using client-generated IDs enables stable optimistic updates.
 */
id?: string, project_id: string, name: string, color: string, sort_order: number, hidden: boolean, };

export type UpdateProjectStatusRequest = { name: string | null, color: string | null, sort_order: number | null, hidden: boolean | null, };

export type CreateIssueRequest = { 
/**
 * Optional client-generated ID. If not provided, server generates one.
 * Using client-generated IDs enables stable optimistic updates.
 */
id?: string, project_id: string, status_id: string, title: string, description: string | null, priority: IssuePriority, start_date: string | null, target_date: string | null, completed_at: string | null, sort_order: number, parent_issue_id: string | null, parent_issue_sort_order: number | null, extension_metadata: JsonValue, };

export type UpdateIssueRequest = { status_id: string | null, title: string | null, description: string | null | null, priority: IssuePriority | null, start_date: string | null | null, target_date: string | null | null, completed_at: string | null | null, sort_order: number | null, parent_issue_id: string | null | null, parent_issue_sort_order: number | null | null, extension_metadata: JsonValue | null, };

export type CreateIssueAssigneeRequest = { 
/**
 * Optional client-generated ID. If not provided, server generates one.
 * Using client-generated IDs enables stable optimistic updates.
 */
id?: string, issue_id: string, user_id: string, };

export type UpdateIssueAssigneeRequest = { user_id: string | null, };

export type CreateIssueFollowerRequest = { 
/**
 * Optional client-generated ID. If not provided, server generates one.
 * Using client-generated IDs enables stable optimistic updates.
 */
id?: string, issue_id: string, user_id: string, };

export type UpdateIssueFollowerRequest = { user_id: string | null, };

export type CreateIssueTagRequest = { 
/**
 * Optional client-generated ID. If not provided, server generates one.
 * Using client-generated IDs enables stable optimistic updates.
 */
id?: string, issue_id: string, tag_id: string, };

export type UpdateIssueTagRequest = { tag_id: string | null, };

export type CreateIssueRelationshipRequest = { 
/**
 * Optional client-generated ID. If not provided, server generates one.
 * Using client-generated IDs enables stable optimistic updates.
 */
id?: string, issue_id: string, related_issue_id: string, relationship_type: IssueRelationshipType, };

export type UpdateIssueRelationshipRequest = { related_issue_id: string | null, relationship_type: IssueRelationshipType | null, };

export type CreateIssueCommentRequest = { 
/**
 * Optional client-generated ID. If not provided, server generates one.
 * Using client-generated IDs enables stable optimistic updates.
 */
id?: string, issue_id: string, message: string, parent_id: string | null, };

export type UpdateIssueCommentRequest = { message: string | null, parent_id: string | null | null, };

export type CreateIssueCommentReactionRequest = { 
/**
 * Optional client-generated ID. If not provided, server generates one.
 * Using client-generated IDs enables stable optimistic updates.
 */
id?: string, comment_id: string, emoji: string, };

export type UpdateIssueCommentReactionRequest = { emoji: string | null, };

// Shape definition interface
export interface ShapeDefinition<T> {
  readonly table: string;
  readonly params: readonly string[];
  readonly url: string;
  readonly _type: T;  // Phantom field for type inference (not present at runtime)
}

// Helper to create type-safe shape definitions
function defineShape<T>(
  table: string,
  params: readonly string[],
  url: string
): ShapeDefinition<T> {
  return { table, params, url } as ShapeDefinition<T>;
}

// Individual shape definitions with embedded types
export const PROJECTS_SHAPE = defineShape<Project>(
  'projects',
  ['organization_id'] as const,
  '/v1/shape/projects'
);

export const NOTIFICATIONS_SHAPE = defineShape<Notification>(
  'notifications',
  ['organization_id', 'user_id'] as const,
  '/v1/shape/notifications'
);

export const ORGANIZATION_MEMBER_METADATA_SHAPE = defineShape<OrganizationMember>(
  'organization_member_metadata',
  ['organization_id'] as const,
  '/v1/shape/organization_members'
);

export const USERS_SHAPE = defineShape<User>(
  'users',
  ['organization_id'] as const,
  '/v1/shape/users'
);

export const TAGS_SHAPE = defineShape<Tag>(
  'tags',
  ['project_id'] as const,
  '/v1/shape/project/{project_id}/tags'
);

export const PROJECT_STATUSES_SHAPE = defineShape<ProjectStatus>(
  'project_statuses',
  ['project_id'] as const,
  '/v1/shape/project/{project_id}/project_statuses'
);

export const ISSUES_SHAPE = defineShape<Issue>(
  'issues',
  ['project_id'] as const,
  '/v1/shape/project/{project_id}/issues'
);

export const WORKSPACES_SHAPE = defineShape<Workspace>(
  'workspaces',
  ['project_id'] as const,
  '/v1/shape/project/{project_id}/workspaces'
);

export const ISSUE_ASSIGNEES_SHAPE = defineShape<IssueAssignee>(
  'issue_assignees',
  ['project_id'] as const,
  '/v1/shape/project/{project_id}/issue_assignees'
);

export const ISSUE_FOLLOWERS_SHAPE = defineShape<IssueFollower>(
  'issue_followers',
  ['project_id'] as const,
  '/v1/shape/project/{project_id}/issue_followers'
);

export const ISSUE_TAGS_SHAPE = defineShape<IssueTag>(
  'issue_tags',
  ['project_id'] as const,
  '/v1/shape/project/{project_id}/issue_tags'
);

export const ISSUE_RELATIONSHIPS_SHAPE = defineShape<IssueRelationship>(
  'issue_relationships',
  ['project_id'] as const,
  '/v1/shape/project/{project_id}/issue_relationships'
);

export const PULL_REQUESTS_SHAPE = defineShape<PullRequest>(
  'pull_requests',
  ['project_id'] as const,
  '/v1/shape/project/{project_id}/pull_requests'
);

export const ISSUE_COMMENTS_SHAPE = defineShape<IssueComment>(
  'issue_comments',
  ['issue_id'] as const,
  '/v1/shape/issue/{issue_id}/comments'
);

export const ISSUE_COMMENT_REACTIONS_SHAPE = defineShape<IssueCommentReaction>(
  'issue_comment_reactions',
  ['issue_id'] as const,
  '/v1/shape/issue/{issue_id}/reactions'
);

// =============================================================================
// Entity Definitions for SDK Generation
// =============================================================================

// Scope enum matching Rust
export type Scope = 'Organization' | 'Project' | 'Issue' | 'Comment';

// Entity definition interface
export interface EntityDefinition<TRow, TCreate = unknown, TUpdate = unknown> {
  readonly name: string;
  readonly table: string;
  readonly mutationScope: Scope | null;
  readonly shapeScope: Scope | null;
  readonly shape: ShapeDefinition<TRow> | null;
  readonly mutations: {
    readonly url: string;
    readonly _createType: TCreate;  // Phantom (not present at runtime)
    readonly _updateType: TUpdate;  // Phantom (not present at runtime)
  } | null;
}

// Individual entity definitions
export const PROJECT_ENTITY: EntityDefinition<Project, CreateProjectRequest, UpdateProjectRequest> = {
  name: 'Project',
  table: 'projects',
  mutationScope: 'Organization',
  shapeScope: 'Organization',
  shape: PROJECTS_SHAPE,
  mutations: { url: '/v1/projects' } as EntityDefinition<Project, CreateProjectRequest, UpdateProjectRequest>['mutations'],
};

export const NOTIFICATION_ENTITY: EntityDefinition<Notification, CreateNotificationRequest, UpdateNotificationRequest> = {
  name: 'Notification',
  table: 'notifications',
  mutationScope: 'Organization',
  shapeScope: 'Organization',
  shape: NOTIFICATIONS_SHAPE,
  mutations: { url: '/v1/notifications' } as EntityDefinition<Notification, CreateNotificationRequest, UpdateNotificationRequest>['mutations'],
};

export const ORGANIZATION_MEMBER_ENTITY: EntityDefinition<OrganizationMember> = {
  name: 'OrganizationMember',
  table: 'organization_member_metadata',
  mutationScope: null,
  shapeScope: null,
  shape: ORGANIZATION_MEMBER_METADATA_SHAPE,
  mutations: null,
};

export const USER_ENTITY: EntityDefinition<User> = {
  name: 'User',
  table: 'users',
  mutationScope: null,
  shapeScope: null,
  shape: USERS_SHAPE,
  mutations: null,
};

export const TAG_ENTITY: EntityDefinition<Tag, CreateTagRequest, UpdateTagRequest> = {
  name: 'Tag',
  table: 'tags',
  mutationScope: 'Project',
  shapeScope: 'Project',
  shape: TAGS_SHAPE,
  mutations: { url: '/v1/tags' } as EntityDefinition<Tag, CreateTagRequest, UpdateTagRequest>['mutations'],
};

export const PROJECT_STATUS_ENTITY: EntityDefinition<ProjectStatus, CreateProjectStatusRequest, UpdateProjectStatusRequest> = {
  name: 'ProjectStatus',
  table: 'project_statuses',
  mutationScope: 'Project',
  shapeScope: 'Project',
  shape: PROJECT_STATUSES_SHAPE,
  mutations: { url: '/v1/project_statuses' } as EntityDefinition<ProjectStatus, CreateProjectStatusRequest, UpdateProjectStatusRequest>['mutations'],
};

export const ISSUE_ENTITY: EntityDefinition<Issue, CreateIssueRequest, UpdateIssueRequest> = {
  name: 'Issue',
  table: 'issues',
  mutationScope: 'Project',
  shapeScope: 'Project',
  shape: ISSUES_SHAPE,
  mutations: { url: '/v1/issues' } as EntityDefinition<Issue, CreateIssueRequest, UpdateIssueRequest>['mutations'],
};

export const WORKSPACE_ENTITY: EntityDefinition<Workspace> = {
  name: 'Workspace',
  table: 'workspaces',
  mutationScope: null,
  shapeScope: null,
  shape: WORKSPACES_SHAPE,
  mutations: null,
};

export const ISSUE_ASSIGNEE_ENTITY: EntityDefinition<IssueAssignee, CreateIssueAssigneeRequest, UpdateIssueAssigneeRequest> = {
  name: 'IssueAssignee',
  table: 'issue_assignees',
  mutationScope: 'Issue',
  shapeScope: 'Project',
  shape: ISSUE_ASSIGNEES_SHAPE,
  mutations: { url: '/v1/issue_assignees' } as EntityDefinition<IssueAssignee, CreateIssueAssigneeRequest, UpdateIssueAssigneeRequest>['mutations'],
};

export const ISSUE_FOLLOWER_ENTITY: EntityDefinition<IssueFollower, CreateIssueFollowerRequest, UpdateIssueFollowerRequest> = {
  name: 'IssueFollower',
  table: 'issue_followers',
  mutationScope: 'Issue',
  shapeScope: 'Project',
  shape: ISSUE_FOLLOWERS_SHAPE,
  mutations: { url: '/v1/issue_followers' } as EntityDefinition<IssueFollower, CreateIssueFollowerRequest, UpdateIssueFollowerRequest>['mutations'],
};

export const ISSUE_TAG_ENTITY: EntityDefinition<IssueTag, CreateIssueTagRequest, UpdateIssueTagRequest> = {
  name: 'IssueTag',
  table: 'issue_tags',
  mutationScope: 'Issue',
  shapeScope: 'Project',
  shape: ISSUE_TAGS_SHAPE,
  mutations: { url: '/v1/issue_tags' } as EntityDefinition<IssueTag, CreateIssueTagRequest, UpdateIssueTagRequest>['mutations'],
};

export const ISSUE_RELATIONSHIP_ENTITY: EntityDefinition<IssueRelationship, CreateIssueRelationshipRequest, UpdateIssueRelationshipRequest> = {
  name: 'IssueRelationship',
  table: 'issue_relationships',
  mutationScope: 'Issue',
  shapeScope: 'Project',
  shape: ISSUE_RELATIONSHIPS_SHAPE,
  mutations: { url: '/v1/issue_relationships' } as EntityDefinition<IssueRelationship, CreateIssueRelationshipRequest, UpdateIssueRelationshipRequest>['mutations'],
};

export const PULL_REQUEST_ENTITY: EntityDefinition<PullRequest> = {
  name: 'PullRequest',
  table: 'pull_requests',
  mutationScope: null,
  shapeScope: null,
  shape: PULL_REQUESTS_SHAPE,
  mutations: null,
};

export const ISSUE_COMMENT_ENTITY: EntityDefinition<IssueComment, CreateIssueCommentRequest, UpdateIssueCommentRequest> = {
  name: 'IssueComment',
  table: 'issue_comments',
  mutationScope: 'Issue',
  shapeScope: 'Issue',
  shape: ISSUE_COMMENTS_SHAPE,
  mutations: { url: '/v1/issue_comments' } as EntityDefinition<IssueComment, CreateIssueCommentRequest, UpdateIssueCommentRequest>['mutations'],
};

export const ISSUE_COMMENT_REACTION_ENTITY: EntityDefinition<IssueCommentReaction, CreateIssueCommentReactionRequest, UpdateIssueCommentReactionRequest> = {
  name: 'IssueCommentReaction',
  table: 'issue_comment_reactions',
  mutationScope: 'Comment',
  shapeScope: 'Comment',
  shape: ISSUE_COMMENT_REACTIONS_SHAPE,
  mutations: { url: '/v1/issue_comment_reactions' } as EntityDefinition<IssueCommentReaction, CreateIssueCommentReactionRequest, UpdateIssueCommentReactionRequest>['mutations'],
};

// Type helper to extract row type from an entity
export type EntityRowType<E extends EntityDefinition<unknown>> = E extends EntityDefinition<infer R> ? R : never;
